#!/usr/bin/env python3
"""
Export QFAN showers in the official CaloChallenge Dataset 1 format.

    pip install h5py
    python ds1/export_calochallenge.py outputs/model_<tag>.npz \\
           --data data/ds1_53.npy --out outputs/qfan_ds1_photons.h5

Writes two files the official CaloChallenge code reads directly:

    qfan_ds1_photons.h5        showers generated by QFAN
    qfan_ds1_photons_ref.h5    the held-out GEANT4 test showers, prepared the
                               same way, for a like-for-like comparison

Each holds `incident_energies` (N, 1) in MeV and `showers` (N, 368) in MeV,
flattened radial-fastest within each layer as the challenge specifies. Load
them into the official HighLevelFeatures class from the CaloChallenge
repository to draw the polar shower plots and compute layer energies.

UNDOING THE ANGLE COLLAPSE

QFAN models each layer's radial profile summed over angle, 53 values instead
of 368 voxels. Here each radial bin's energy is spread evenly over the angular
bins of its layer. That conserves the energy of every radial ring and every
layer exactly, so layer energies and radial profiles are faithful.

What it cannot restore is angular structure within a ring: every exported
shower is azimuthally uniform by construction. Averaged over many showers this
matches GEANT4 closely, since electromagnetic showers are nearly azimuthally
symmetric; for single showers the rings will look smoother than the truth.
The reference file is prepared the same way, so the average-shower plots
compare like with like. Evaluate the model on the observables it can carry
honestly: layer energies and radial profiles.

UNDOING THE NORMALIZATION

The stored images are energy fractions scaled for training, with a global or
per-pixel factor recorded in the .json beside the data file. They are mapped
back to MeV exactly; only values that were clipped during preprocessing, the
top 0.1%, cannot be recovered and stay at the clip value.
"""
import argparse
import json
import pathlib
import sys

import numpy as np

# (n_alpha, n_r) per layer, photons, in image order (see prepare_ds1.py)
LAYERS = [(1, 8), (10, 16), (10, 19), (1, 5), (1, 5)]
N_VOX = sum(a * r for a, r in LAYERS)                        # 368
N_COLLAPSED = sum(r for _, r in LAYERS)                      # 53


def expand(collapsed):
    """(N, 53) radial profiles -> (N, 368) voxels, energy spread evenly over
    the angular bins of each ring. Voxels are radial-fastest within a layer."""
    collapsed = np.asarray(collapsed, np.float64)
    if collapsed.shape[1] != N_COLLAPSED:
        raise ValueError(f"expected {N_COLLAPSED} values, got {collapsed.shape[1]}")
    out, c = [], 0
    for n_a, n_r in LAYERS:
        ring = collapsed[:, c:c + n_r] / n_a                 # (N, n_r)
        out.append(np.tile(ring, (1, n_a)))                  # alpha-major blocks
        c += n_r
    return np.concatenate(out, axis=1)


def collapse(voxels):
    """(N, 368) -> (N, 53), summing over angle. Inverse of expand()."""
    voxels = np.asarray(voxels, np.float64)
    out, c = [], 0
    for n_a, n_r in LAYERS:
        out.append(voxels[:, c:c + n_a * n_r].reshape(-1, n_a, n_r).sum(1))
        c += n_a * n_r
    return np.concatenate(out, axis=1)


def unring(image):
    """(N, 368) ring-major -> (N, 368) in the challenge's own order
    (radial fastest within each angular slice), layer by layer."""
    image = np.asarray(image, np.float64)
    out, c = [], 0
    for n_a, n_r in LAYERS:
        blk = image[:, c:c + n_a * n_r].reshape(-1, n_r, n_a)
        out.append(blk.transpose(0, 2, 1).reshape(len(image), -1))
        c += n_a * n_r
    return np.concatenate(out, axis=1)


def to_voxels(image, info):
    """Any image produced by prepare_ds1.py -> (N, 368) voxels in MeV, in
    the challenge's voxel order."""
    mev = to_mev(image, info)
    if info.get("collapse") == "angle":
        return expand(mev)
    if info.get("collapse") == "none":
        return unring(mev) if info.get("order") == "ring" else mev
    raise ValueError(f"unsupported image: collapse={info.get('collapse')}")


def to_mev(image, info):
    """Undo the preprocessing of prepare_ds1.py: training units -> MeV."""
    e_inc = float(info["energy_mev"])
    if info.get("pixel_scale"):
        frac = image / np.asarray(info["pixel_scale"], float)[None, :]
    else:
        frac = image / float(info["energy_scale"])
    return frac * e_inc


def self_test():
    rng = np.random.default_rng(0)
    x = rng.random((50, N_COLLAPSED))
    v = expand(x)
    assert v.shape == (50, N_VOX)
    assert np.allclose(collapse(v), x), "collapse(expand(x)) != x"
    # every ring's energy is conserved
    assert np.allclose(v.sum(1), x.sum(1)), "total energy not conserved"
    # a segmented layer really is uniform in angle
    L = v[:, 8:168].reshape(50, 10, 16)
    assert np.allclose(L, L[:, :1, :]), "layer 1 not azimuthally uniform"
    # the layout matches prepare_ds1: voxel (layer 2, alpha 3, r 7)
    s = 8 + 160                                              # start of layer 2
    one = np.zeros((1, N_COLLAPSED)); one[0, 8 + 16 + 7] = 10.0
    ve = expand(one)
    assert np.isclose(ve[0, s + 3 * 19 + 7], 1.0), "voxel ordering wrong"
    # physical units round-trip for both normalizations
    img = rng.random((5, N_COLLAPSED)) * 0.5
    g = dict(energy_mev=65536, energy_scale=1.908)
    assert np.allclose(to_mev(img, g), img / 1.908 * 65536)
    ps = list(rng.random(N_COLLAPSED) + 0.5)
    p = dict(energy_mev=65536, pixel_scale=ps)
    assert np.allclose(to_mev(img, p), img / np.array(ps) * 65536)
    # ring order round trip against the loader's own ring ordering
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
    from prepare_ds1 import ds1_to_image
    raw = rng.random((7, N_VOX)) + 0.01
    ring, _ = ds1_to_image(raw, np.ones(7), "photons", "none", order="ring",
                           target=1e12, clip_quantile=1.0)
    std, _ = ds1_to_image(raw, np.ones(7), "photons", "none", order="standard",
                          target=1e12, clip_quantile=1.0)
    assert np.allclose(unring(ring), std), "unring does not invert the ring order"
    print("[SELF-TEST] expand/collapse round trip, energy conservation, "
          "azimuthal uniformity, voxel ordering and unit conversion verified")


def write_h5(path, showers_mev, e_inc):
    try:
        import h5py
    except ImportError:
        sys.exit("h5py is required: pip install h5py")
    n = len(showers_mev)
    with h5py.File(path, "w") as f:
        f.create_dataset("incident_energies",
                         data=np.full((n, 1), float(e_inc)),
                         compression="gzip")
        f.create_dataset("showers", data=showers_mev.astype(np.float32),
                         compression="gzip")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("model", nargs="?", help="outputs/model_<tag>.npz")
    ap.add_argument("--data", help="the .npy the model was trained on")
    ap.add_argument("--out", default="outputs/qfan_ds1_photons.h5")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        self_test()
        return
    if not a.model or not a.data:
        ap.error("model and --data are required (or use --self-test)")

    side = pathlib.Path(a.data).with_suffix(".json")
    if not side.exists():
        sys.exit(f"missing {side}; it is written by prepare_ds1.py")
    info = json.loads(side.read_text())
    if info.get("particle", "photons") != "photons":
        sys.exit("this exporter handles photons")

    r = np.load(a.model, allow_pickle=True)
    gen = to_voxels(r["Y_gen"], info)
    ref = to_voxels(r["Y_te"], info)
    out = pathlib.Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    ref_path = out.with_name(out.stem + "_ref" + out.suffix)
    write_h5(out, gen, info["energy_mev"])
    write_h5(ref_path, ref, info["energy_mev"])
    print(f"[EXPORT] {out}        {gen.shape}  QFAN")
    print(f"[EXPORT] {ref_path}  {ref.shape}  GEANT4 test showers, same preparation")
    print(f"         incident energy {info['energy_mev']} MeV; mean deposited "
          f"energy QFAN {gen.sum(1).mean():.0f} MeV, GEANT4 {ref.sum(1).mean():.0f} MeV")


if __name__ == "__main__":
    main()
